version: "3.7"
services:
  web:
    container_name: carts
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=1200
    ports:
      - 9100:9100
    volumes:
      - .:/app